#coding:utf8
"""
Django settings for Blog project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_ROOT = 'D:/'
MEDIA_URL ='/media/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '457i+e)051=&6%wq=+cxqv1f*8u7+p#r0(o)plvut^$)$4jcyo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'recall',
    'django.contrib.staticfiles',
   # 'django.contrib.sites',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Blog.urls'

LOGIN_URL = '/qqlogin/'
LOGIN_REDIRECT_URL = '/profile/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.core.context_processors.i18n',
                
            ],
        },
    },
]


SOCIALOAUTH_SITES = (
    ('qq', 'socialoauth.sites.qq.QQ', 'QQ',
        {
          'redirect_uri': 'http://www.xungongming.cn/qqlogin',
          'client_id': '101220574',
          'client_secret': '492fb7549c6d6b5e151120e2451824c6',
        }
    ),
)



# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': 'mypostgres',
        'USER': 'postgres',
        'PASSWORD': '020201',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-CN'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class':'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'mylogger': {
            'handlers' : ['console',],
            'level': 'DEBUG'
        }
    }
}
#AUTHENTICATION_BACKENDS = (
#    'social_auth.backends.contrib.qq.QQBackend',
#    'social_auth.backends.facebook.FacebookBackend',
#    'social_auth.backends.google.GoogleOAuthBackend',
#    'social_auth.backends.google.GoogleOAuth2Backend',
#    'social_auth.backends.google.GoogleBackend',
#    'social_auth.backends.yahoo.YahooBackend',
#    'social_auth.backends.browserid.BrowserIDBackend',
#    'social_auth.backends.contrib.linkedin.LinkedinBackend',
#    'social_auth.backends.contrib.disqus.DisqusBackend',
#    'social_auth.backends.contrib.livejournal.LiveJournalBackend',
#    'social_auth.backends.contrib.orkut.OrkutBackend',
#    'social_auth.backends.contrib.foursquare.FoursquareBackend',
#    'social_auth.backends.contrib.github.GithubBackend',
#    'social_auth.backends.contrib.vk.VKOAuth2Backend',
#    'social_auth.backends.contrib.live.LiveBackend',
#    'social_auth.backends.contrib.skyrock.SkyrockBackend',
#    'social_auth.backends.contrib.yahoo.YahooOAuthBackend',
#    'social_auth.backends.contrib.readability.ReadabilityBackend',
#    'social_auth.backends.contrib.fedora.FedoraBackend',
#    'social_auth.backends.OpenIDBackend',
#    'django.contrib.auth.backends.ModelBackend',
#)
#SOCIAL_AUTH_QQ_KEY = '101220574'
#SOCIAL_AUTH_QQ_SECRET = '492fb7549c6d6b5e151120e2451824c6'
#
#SOCIAL_AUTH_PIPELINE = (
#    'social.pipeline.social_auth.social_details',
#    'social.pipeline.social_auth.social_uid',
#    'social.pipeline.social_auth.auth_allowed',
#    'social.pipeline.partial.save_status_to_session',
#    'social.pipeline.social_auth.save_authentication_user_detail_to_session',
#)
#SOCIAL_AUTH_DISCONNECT_PIPELINE = (
#    'social.pipeline.disconnect.allowed_to_disconnect',
#    'social.pipeline.disconnect.get_entries',
#    'social.pipeline.disconnect.revoke_tokens',
#    'social.pipeline.disconnect.disconnect'
#)
#SOCIAL_AUTH_LOGIN_URL = '/login-url'
#SOCIAL_AUTH_LOGIN_ERROR_URL = '/login-error'
#SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/logged-in'
#SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/new-users-redirect-url'
#SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = '/oauth/newassociation'
#SOCIAL_AUTH_BACKEND_ERROR_URL = '/new-error-url'
#SOCIAL_AUTH_AUTHENTICATION_SUCCESS_URL = '/oauth/authentication/success'
#SOCIAL_AUTH_SANITIZE_REDIRECTS = False
#LOGIN_REDIRECT_URL = 'http://llovebaimuda.herokuapp.com/'
#WSGI_APPLICATION = 'Blog.wsgi.application'
#
#
##SOCIAL_AUTH_ENABLED_BACKENDS =('qq','google','yahoo')
#GOOGLE_OAUTH2_CLIENT_ID = '1000101'
#GOOGLE_OAUTH2_CLIENT_SECRET = '000000'
#TWITTER_CONSUMER_KEY         = ''
#TWITTER_CONSUMER_SECRET      = ''
#FACEBOOK_APP_ID              = ''
#FACEBOOK_API_SECRET          = ''
#LINKEDIN_CONSUMER_KEY        = ''
#LINKEDIN_CONSUMER_SECRET     = ''
#ORKUT_CONSUMER_KEY           = ''
#ORKUT_CONSUMER_SECRET        = ''
#GOOGLE_CONSUMER_KEY          = ''
#GOOGLE_CONSUMER_SECRET       = ''
#GOOGLE_OAUTH2_CLIENT_ID      = ''
#GOOGLE_OAUTH2_CLIENT_SECRET  = ''
#FOURSQUARE_CONSUMER_KEY      = ''
#FOURSQUARE_CONSUMER_SECRET   = ''
#VK_APP_ID                    = ''
#VK_API_SECRET                = ''
#LIVE_CLIENT_ID               = ''
#LIVE_CLIENT_SECRET           = ''
#SKYROCK_CONSUMER_KEY         = ''
#SKYROCK_CONSUMER_SECRET      = ''
#YAHOO_CONSUMER_KEY           = '1002001'
#YAHOO_CONSUMER_SECRET        = '102010203021'
#READABILITY_CONSUMER_SECRET  = ''
#READABILITY_CONSUMER_SECRET  = ''
#SOCIAL_AUTH_COMPLETE_URL_NAME=''
